spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /mazebank

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

mongo:
  connection:
    url: ${MONGO_CONNECTION_URL:mongodb://127.0.0.1:27017}