server:
  port: ${PORT:8080}
  servlet:
    context-path: /mazebank

mongo:
  connection:
    url: ${MONGO_CONNECTION_URL:mongodb+srv://mazebank:mazebank@mazebankcluster.dddrndp.mongodb.net/?retryWrites=true&w=majority}