apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mazebank
resources:
  - namespace.yaml
  - configmap.yaml
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
