apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazebank
  namespace: mazebank
  labels:
    app: mazebank
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mazebank
  template:
    metadata:
      labels:
        app: mazebank
    spec:
      containers:
        - name: mazebank
          image: 650468121963.dkr.ecr.us-east-2.amazonaws.com/mzb/mazebank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: mazebank-config
            - secretRef:
                name: mazebank-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /mazebank/actuator/health/readiness
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /mazebank/actuator/health/liveness
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
