apiVersion: v1
kind: Secret
metadata:
  name: mazebank-secrets
  namespace: mazebank
type: Opaque
stringData:
  MONGO_CONNECTION_URL: "mongodb+srv://username:password@cluster.example.mongodb.net/?retryWrites=true&w=majority"
