replicaCount: 1

image:
  repository: mazebankacr.azurecr.io/mazebank
  pullPolicy: Always
  tag: "1.5.0"

namespace: mazebank

config:
  springProfilesActive: prod
  port: "8080"
  mongoConnectionUrl: "" # Injetado via ConfigMap no deploy a partir de ENV/real/env.conf

secret:
  create: false

service:
  type: ClusterIP      # Mudou de LoadBalancer para ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true        # Mudou de false para true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: mazebank-app.brazilsouth.cloudapp.azure.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mazebank-tls-secret
      hosts:
        - mazebank-app.brazilsouth.cloudapp.azure.com

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi

probes:
  readiness:
    path: /mazebank/actuator/health/readiness
    initialDelaySeconds: 25
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  liveness:
    path: /mazebank/actuator/health/liveness
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  startup:
    enabled: true
    path: /mazebank/actuator/health/liveness
    periodSeconds: 5
    failureThreshold: 30

mongodb:
  enabled: false # Utiliza MongoDB Atlas externalizado configurado em env.conf
