apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mazebank.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "mazebank.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mazebank.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mazebank.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.mongodb.enabled }}
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mongo {{ .Values.mongodb.port }}; do
                echo "waiting for mongo..."
                sleep 2
              done
      {{- end }}
      containers:
        - name: {{ include "mazebank.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.port | int }}
              name: http
          envFrom:
            - configMapRef:
                name: mazebank-config
            {{- if .Values.secret.create }}
            - secretRef:
                name: mazebank-secrets
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            {{- if gt (.Values.probes.readiness.initialDelaySeconds | int) 0 }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            {{- end }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            {{- if gt (.Values.probes.liveness.initialDelaySeconds | int) 0 }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            {{- end }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
